### ISSUE TITLE
Implement eslint and phpcs code style checks

### ISSUE THREAD

**Issue by kadamwhite** [wikimedia/interconnection-wordpress-theme#4]
The [shiro theme](https://github.com/wikimedia/shiro-wordpress-theme) has ESLint and PHPCS set up to enforce reasonable code style consistency and catch syntax errors, security risks, and inefficient queries. The same coding standards should be applied to this repository for consistency.

- [ ] PRs are checked against ESLint standards
- [ ] PRs are checked against PHPCS standards
- [ ] PRs are checked against Stylelint standards

**Comment by kadamwhite** [comment]
Also needs to have Stylelint, which can [break the build](https://github.com/wikimedia/interconnection-wordpress-theme/actions/runs/4016041937) if errors are present.

**Comment by sanjaymalladi** [comment]
actually i want to contribute to this issue please assign me this issue

**Comment by kadamwhite** [comment]
Addressed enough in the below PRs that we can probably close this out

- #46 
- #47
